converter = {
    # Income Statements
    "Chi phí hoạt động khác": "cost",
    "Chi phí trực tiếp kinh doanh hoạt động khác": "cost",
    "Lãi trên cổ phiếu pha loãng": "eps",
    "Chi phí hoạt động tự doanh ": "cost",
    "Thu đòi người thứ ba": "none",
    "Chi phí khác": "cost",
    "Thu nhập từ hoạt động dịch vụ": "income",
    "Thu nhập khác hoạt động kinh doanh bảo hiểm ": "iitsa",
    "Lợi nhuận chưa thực hiện": "unearned_revenue",
    "Thu nhập lãi và các khoản thu nhập tương tự": "income",
    "Lợi ích cổ đông thiểu số ": "profit",
    "Tổng chi trực tiếp hoạt động kinh doanh bảo hiểm": "total_cost",
    "Thu khác nhượng tái bảo hiểm ": "income",
    "Chi đòi người thứ ba": "cost",
    "Chi phí tài chính": "cost",
    "Các khoản giảm trừ": "deduction",
    "Lãi/lỗ đánh giá công cụ phái sinh": "glce",
    "Các khoản giảm từ chi phí": "cost_deduction",
    "Doanh thu hoạt động tài chính ": "sales",
    "Lợi nhuận của Cổ đông của Công ty mẹ": "profit",
    "Doanh thu hoạt động ủy thác, đấu giá": "sales",
    "Lãi thuần từ hoạt động dịch vụ": "profit",
    "Thu nhập toàn diện phân bổ cho chủ sở hữu": "income",
    "Chi khác nhận tái bảo hiểm khác": "cost",
    "Chi phí lãi vay, lỗ từ các khoản cho vay và phải thu": "cost",
    "Chi bồi thường bảo hiểm gốc và chi trả đáo hạn": "cost",
    "Chi phí lãi vay  ": "cost",
    "Lãi/lỗ từ công ty liên doanh, liên kết ": "glce",
    "Doanh thu khác": "sales",
    "Lãi/(lỗ) thuần từ mua bán chứng khoán kinh doanh": "glce",
    "Lợi nhuận sau thuế": "ebi",
    "Chi đề phòng hạn chế tổn thất": "expense",
    "Lãi/(lỗ) thuần sau thuế": "glce",
    "CP dự phòng TSTC, xử lý tổn thất các khoản phải thu khó đòi và lỗ suy giảm TSTC và CP đi vay": "cost",
    "Thu nhập thuần trên cổ phiếu phổ thông": "income",
    "Chi phí hoạt động ": "cost",
    "Doanh thu khác về đầu tư": "sales",
    "Doanh số": "revenue",
    "chi phí hoạt động dịch vụ": "cost",
    "Kết quả hoạt động": "none",
    "Lãi từ các công cụ phát sinh phòng ngừa rủi ro": "profit",
    "Lãi cơ bản trên cổ phiếu": "eps",
    "Chênh lệch lãi tỷ giá hối đoái đã và chưa thực hiện": "exchange",
    "Thu nhập từ hoạt động khác": "income",
    "Chi phí bán hàng ": "cost",
    "Thu hoa hồng nhượng tái bảo hiểm ": "income",
    "Lãi/lỗ từ đánh giá lại các công cụ tài chính phái sinh": "glce",
    "Lãi/lỗ chêch lệch tỷ giá của hoạt động tại nước ngoài": "glce",
    "Tăng/giảm dự phòng bồi thường": "expense",
    "Doanh thu hoạt động tư vấn tài chính": "sales",
    "Chi phí tài chính khác": "cost",
    "LNST trích các Quỹ dự trữ điều lệ, Quỹ dự phòng tài chính và RR nghề nghiệp theo quy định điều lệ Công ty": "ebi",
    "Các khoản giảm từ khác": "deduction",
    "Thu nhập lãi thuần": "income",
    "Thu nhập từ hoạt động khác ": "income",
    "Chi phí quản lý công ty chứng khoán": "cost",
    "Giảm phí": "deduction",
    "Chi phí bán hàng(trước 2014)": "cost",
    "Thu nhập toàn diện phân bổ cho cổ đông không kiểm soát": "income",
    "Chi bán hàng": "cost",
    "Lãi bán các tài sản tài chính": "profit",
    "Chi bồi thường tư quỹ dao động lớn ": "cost",
    "Lỗ thuần từ hoạt động bảo hiểm nhân thọ": "lost",
    "Lãi từ các khoản cho vay và phải thu": "profit",
    "Thu nhập khác ròng": "income",
    "Dự phòng đảm bảo cân đối": "expense",
    "Lỗ bán, thanh lý các khoản đầu tư vào công ty con, liên kết, liên doanh": "lost",
    "Chi phí quản lý doanh  nghiệp": "cost",
    "Chi giám định, đánh giá rủi ro đối đượng được bảo hiểm, chi khác ": "cost",
    "Chi phí hoạt động tài chính ": "cost",
    "Lỗ các khoản đầu tư nắm giữ đến ngày đáo hạn (HTM)": "lost",
    "Chi phí thuế TNDN hoãn lại": "cost",
    "Chi phí của hoạt động ngân hàng ": "cost",
    "Lợi nhuận gộp hoạt động kinh doanh bảo hiểm": "profit",
    "Chi phí hoạt động": "cost",
    "Cổ tức, tiền lãi phát sinh từ tài sản tài chính FVTPL": "profit",
    "Chi phí quản lý doanh nghiệp liên quan đến các lĩnh vực khác ": "cost",
    "Lợi nhuận thuần hoạt động ngân hàng ": "profit",
    "Thu nhập từ góp vốn, mua cổ phần": "income",
    "Các khoản giảm trừ doanh thu": "income_deduction",
    "Thu nhập (lỗ) toàn diện khác sau thuế TNDN": "ebi",
    "Tăng/giảm dự phòng bồi thường nhượng tái bảo hiểm ": "cashflow",
    "Thu nhập thuần từ hoạt động ngân hàng ": "income",
    "Chi xử lý hàng bồi thường 100%": "cost",
    "Chi phí hoạt đông tư vấn tài chính": "cost",
    "Tổng chi bồi thường bảo hiểm ": "total_cost_ins",
    "Lãi/lỗ từ đánh giá lại các khoản đầu tư giữ đến ngày đáo hạn": "glce",
    "Chi khác hoạt động bảo hiểm gốc": "cost",
    "Chi nhượng tái bảo hiểm ": "cost",
    "LN thuần từ hoạt động kinh doanh trước CF dự phòng rủi ro tín dụng": "profit",
    "Chêch lệch giảm đánh giá lại các tài sản tài chính FVTPL": "none",
    "Lãi từ các tài sản tài chính sẵn sàng để bán (AFS)": "profit",
    "Chi phí bán hàng": "cost",
    "Tổng lợi nhuận kế toán trước thuế": "total_ebt",
    "Cổ đông của Công ty mẹ": "none",
    "Lãi/lỗ từ các khoản đầu tư vào công ty con, công ty liên kết, liên doanh chưa chia": "glce",
    "Thu nhập khác": "income",
    "Thu nhập pha loãng trên cổ phiếu": "income",
    "Thu bồi thường nhượng tái bảo hiểm (Trước 2014)": "profit",
    "Chi phí thuế thu nhập hiện hành": "cost",
    "Chi phí các dịch vụ khác": "cost",
    "Lợi nhuận thuần từ các hoạt động khác ": "profit",
    "Doanh số thuần": "net_revenue",
    "Lỗ từ các tài sản tài chính phái sinh phòng ngừa rủi ro ": "lost",
    "Doanh thu thuần từ hoạt động kinh doanh bảo hiểm ": "sales",
    "Chi phí dự phòng rủi ro tín dụng": "cost",
    "Chi phí hoạt động bảo lãnh, đại lý phát hành chứng khoán": "cost",
    "Lãi/(lỗ) thuần từ hoạt động khác": "glce",
    "Lãi/(lỗ) thuần từ hoạy động kinh doanh ngoại hối và vàng": "glce",
    "     Thuế thu nhập doanh nghiệp – hiện thời": "tax",
    "Thu họat động khác ": "revenue",
    "Doanh thu thuần về hoạt động kinh doanh": "sales",
    "Lãi/lỗ đánh giá lại tài sản cố định theo mô hình giá trị hợp lý": "glce",
    "Bồi thường thuộc trách nhiệm giữ lại": "compensation",
    "Lỗ các tài sản tài chính ghi nhận thông qua lãi lỗ (FVTPL)": "lost",
    "Lợi nhuận thuần hoạt động kinh doanh bảo hiểm ": "profit",
    "Lợi nhuận hoạt động tài chính": "profit",
    "Chi khác": "cost",
    "Lãi từ các khoản đầu tư nắm giữ đến ngày đáo hạn (HTM)": "profit",
    "Lợi nhuận sau thuế phân bổ cho chủ sở hữu": "ebi",
    "Chi phí quản lý liên quan trực tiếp tới hoạt động ngân hàng": "cost",
    "Chi phí thuế thu nhập doanh nghiệp": "cost",
    "Thu nhập hoạt động khác": "income",
    "Chêch lệch lỗ tỷ giá hối đoái đã và chưa thực hiện": "lost",
    "Chêch lệch lãi tỷ giá hối đoái đã và chưa thực hiện":"exchange",
    "Thu nhập tài chính": "income",
    "Lãi từ các tài sản tài chính ghi nhận thông qua lãi/lỗ ( FVTPL)": "profit",
    "Thuế thu nhập doanh nghiệp – hoãn lại": "tax",
    "Doanh thu đại lý phát hành chứng khoán": "sales",
    "Doanh thu phí bảo hiểm": "sales",
    "Lợi nhuận sau thuế thu nhập doanh nghiệp": "ebi",
    "Lãi/lỗ toàn diện khác được chia từ hoạt động đầu tư vào công ty con, đầu tư liên kết, liên doanh": "glce",
    "Thu phí bảo hiểm ": "revenue",
    "Hoàn phí": "none",
    "Thuế thu nhập doanh nghiệp – hiện thời": "tax",
    "Chi phí lãi và các chi phí tương tự": "cost",
    "Chi phí lưu ký chứng khoán": "cost",
    "Giá vốn hàng bán": "cogs",
    "Doanh thu bảo lãnh phát hành chứng khoán": "sales",
    "Phí nhượng tại bảo hiểm ": "cost",
    "Tổng lợi nhuận trước thuế": "total_ebt",
    "     Thuế thu nhập doanh nghiệp – hoãn lại": "tax",
    "Chi phí tư vấn đầu tư chứng khoán": "cost",
    "Lãi/(lỗ) từ hoạt động kinh doanh": "glce",
    "Doanh thu, dự thu cổ tức, lãi tiền gửi không cố định phát sinh trong kỳ": "sales",
    "Lợi nhuận gộp": "gross-profit",
    "Lỗ và ghi nhận chêch lệch đánh giá theo giá trị hợp lý tài sản tài chính sẵn sàng để bán (AFS)": "lost",
    "Thu nhập thuần từ hoạt động khác ": "income",
    "Lãi/(lỗ) từ công ty liên doanh": "glce",
    "Doanh thu hoạt động môi giới chứng khoán": "sales",
    "Doanh thu hoạt động tư vấn đầu tư chứng khoán": "sales",
    "Hoa hồng nhượng tái bảo hiểm và doanh thu HĐKD bảo hiểm ": "sales",
    "Chi bồi thường nhận tái bảo hiểm": "cost",
    "Lãi gộp": "interest",
    "Lãi thuần từ hoạt động bảo hiểm phi nhân thọ": "none",
    "Tổng thu nhập hoạt động": "total_income",
    "Lợi nhuận đã thực hiện": "profit",
    "Lãi/lỗ từ đánh giá lại các tài sản tài chính sẵn sàng để bán": "glce",
    "Doanh thu hoạt động": "sales",
    "Lãi/(lỗ) thuần từ mua bán chứng khoán đầu tư": "glce",
    "Phần lợi nhuận từ đầu tư vào công ty liên kết, liên doanh ": "profit",
    "Thu phí nhận tái bảo hiểm ": "profit",
    "Chi hoa hồng bảo hiểm gốc": "none",
    "Thu nhập từ hoạt động ngân hàng": "income",
    "Lãi/lỗ từ công ty liên doanh (trước 2015)": "glce",
    "Chi phí dự phòng suy giảm giá trị các khoản đầu tư tài chính dài hạn": "cost",
    "Lợi ích của cổ đông thiểu số": "profit",
    "Tăng/giảm dự phòng phí bảo hiểm ": "none",
    "Thu cho thuê sử dụng tài sản ": "none",
    "Chi phí môi giới chứng khoán": "cost",
    "Doanh thu lưu ký chứng khoán": "sales",
    "Thu xử lý hàng bồi thường 100%": "cost",
    "Chi phí thuế TNDN hiện hành": "cost",
    "Chêch lệch tăng đánh giá lại các tài sản tài chính thông qua lãi/lỗ": "none",
    "Lỗ bán các tài sản tài chính": "none",
    "Tăng/giảm dự phòng toán học": "none",
    "Chi phí quản lý doanh nghiệp liên quan trực tiếp đến hoạt động bảo hiểm ": "cost",
    "Chi phí thuế thu nhập hoãn lại": "cost",
    "Lợi nhuận hoạt động khác ": "profit",
    "Lợi nhuận kế toán sau thuế": "ebi",
    "Doanh thu hoạt động tài chính": "sales",
    "Lãi/lỗ từ công ty liên doanh, liên kết (từ 2015)": "glce",
    "Doanh thu hoạt động đầu tư chứng khoán, góp vốn": "sales",
    "Doanh thu phí bảo hiểm thuần ": "sales",
    "Tăng do dự phòng phí chưa được hưởng và dự phòng toán học (trước 2014)": "none",
    "Tổng phí nhượng tái bảo hiểm ": "total_cost_insurance",
    "Lợi nhuận sau thuế của chủ sở hữu, tập đoàn": "ebi",
    "Trong đó: Chi phí lãi vay": "cost",
    "Chi phí hoạt động đấu giá, ủy thác": "cost",
    "Chi phí hoạt động kinh doanh": "cost",
    "Lãi/(lỗ) ròng trước thuế": "glce",
    "Thu nhập khác, ròng": "income",
    "Chi phí giao dịch mua các tài sản tài chính FVTPL": "cost",
    "Lãi cơ bản trên cổ phiếu ": "none",
    "Lãi bán, thanh lý các khoản đầu tư vào công ty con, liên kết, liên doanh": "none",
    "Tăng/giảm dự phòng bồi thường bảo hiểm gốc và nhận tái bảo hiểm ": "none",
    "Trích dự phòng dao động lớn": "none",
    "Thu khác nhận tái bảo hiểm ": "income",
    "Chi khác hoạt động kinh doanh bảo hiểm ": "cost",

# Balance sheet    

    "Dự phòng suy giảm giá trị tài sản dài hạn": "none",
    "Dự phòng đầu tư ngắn hạn": "none",
    "Đầu tư ngắn hạn ": "none",
    "Trái phiếu phát hành ngắn hạn": "none",
    "LỢI NHUẬN ĐÃ PHÂN PHỐI CHO NHÀ ĐẦU TƯ": "profit",
    "Nguyên giá": "cogs",
    "Chứng khoán đầu tư giữ đến ngày đáo hạn": "none",
    "Nợ dài hạn": "debt_lt",
    "Dự phòng chia lãi (trước 2014)": "none",
    "Giá trị ròng bất động sản đầu tư": "none",
    "Chi phí trả trước ngắn hạn": "cost",
    "Phải trả cổ tức, gốc và lãi trái phiếu": "none",
    "Quỹ dự trữ điều lệ": "none",
    "Phải thu về cho vay dài hạn": "receivable",
    "Vốn đầu tư của chủ sở hữu": "equity",
    "Lợi nhuận chưa thực hiện": "profit",
    "Quỹ đầu tư và phát triển ": "invested_capital",
    "Dự phòng giảm giá hàng tồn kho": "none",
    "Thuế giá trị gia tăng được khấu trừ": "none",
    "Dự phòng bảo đảm cân đối (trước 2014)": "none",
    "Dự phòng phí chưa được hưởng (trước 2014)": "none",
    "Cầm cố, thế chấp, ký quỹ và ký cược dài hạn": "none",
    "Dự phòng các khoản phải trả ngắn hạn": "none",
    "Các khoản tài chính sẵn sàng để bán (AFS)": "none",
    "Hàng tồn kho  ": "inventory",
    "Phải thu khác của khách hàng ": "receivable",
    "Trái phiếu chuyển đổi dài hạn": "none",
    "TỔNG CỘNG NGUỒN VỐN": "equity",
    "Dự phòng giảm giá đầu tư tài chính ": "none",
    "Dự phòng giảm giá chứng khoán kinh doanh ": "none",
    "LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ (trước 2015)": "none",
    "Đầu tư vào các công ty con": "invested_capital",
    "LNST chưa phân phối kỳ này": "profit",
    "Tài sản thiếu chờ xử lý": "asset",
    "Dự phòng nghiệp vụ bảo hiểm (trước 2014)": "expense",
    "Giá trị thuần đầu tư tài sản tài chính ngắn hạn ": "none",
    "Hàng tồn kho (Ròng)": "inventory",
    "Phải trả tổ chức phát hành chứng khoán": "none",
    "Quỹ phát triển khoa học và công nghệ": "none",
    "Phải trả người bán": "none",
    "Thuế và các khoản phải nộp nhà nước ": "none",
    "Phải thu khác": "receivable",
    "GTCL TSCĐ hữu hình": "none",
    "Các khoản đầu tư tài chính dài hạn": "invested_capital",
    "Các khoản phải trả, phải nộp khác": "payable",
    "VỐN CHỦ SỞ HỮU": "equity",
    "Dự phòng phải thu dài hạn": "expense",
    "Quỹ hỗ trợ sắp xếp doanh nghiệp": "capital",
    "Phải trả về xây dựng cơ bản ": "payable",
    "Lợi ích cổ đông không kiểm soát": "none",
    "Tài sản dở dang dài hạn": "asset",
    "Đánh giá BĐSĐT theo giá trị hợp lý": "none",
    "Vay nợ ngắn hạn": "debt",
    "Trả trước người bán": "asset_st",
    "Người mua trả tiền trước dài hạn": "none",
    "Chi phí trả trước ngắn hạn khác": "cost",
    "Giá trị hao mòn lũy kế": "none",
    "Chứng khoán đầu tư sẵn sàng để bán": "none",
    "Lợi thế thương mại": "none",
    "    Chứng khoán kinh doanh": "none",
    "LNST chưa phân phối lũy kế đến cuối kỳ trước": "none",
    "Chi phí phải trả dài hạn": "cost",
    "Các khoản phải thu khác": "receivable",
    "Tiền và tương đương tiền": "none",
    "Trả trước dài hạn": "asset_lt",
    "GTCL Tài sản thuê tài chính": "asset",
    "Dự phòng dao động lớn (trước 2014)": "none",
    "Nợ thuê tài chính dài hạn": "debt_lt",
    "Vốn điều lệ": "none",
    "Tiền": "none",
    "Phải thu khác ": "receivable",
    "Nợ ngắn hạn": "none",
    "Phải thu dài hạn khác": "receivable_lt",
    "Chứng khoán đầu tư": "none",
    "Chi phí hoa hồng chưa phân bổ": "cost",
    "Dự phòng đảm bảo cân đối": "expense",
    "Dự phòng nợ khó đòi": "expense",
    "Phải thu khách hàng": "receivable",
    "Dự phòng suy giảm giá trị các khoản phải thu": "expense",
    "Tổng nợ phải trả": "total_liabilities",
    "Phải trả người bán ngắn hạn": "payable",
    "Tài sản thuế thu nhập hoãn lại": "asset",
    "Quỹ đầu tư và phát triển": "invested_capital",
    "Đầu tư chứng khoán dài hạn": "invest_lt",
    "Nợ thuê tài chính ngắn hạn": "debt_st",
    "Các khoản nợ khác": "debt",
    "Vốn chủ sở hữu": "equity",
    "Chứng khoán kinh doanh": "stock",
    "Dự phòng các khoản phải trả ngắn hạn ": "expense",
    "Vay và nợ dài hạn ": "debt_lt",
    "Dự phòng các khoản phải thu khó đòi": "expense",
    "Vay và nợ ngắn hạn": "debt",
    "Đầu tư dài hạn khác": "invest",
    "Tài sản cố định thuê tài chính": "asset",
    "Phải trả nội bộ": "payable",
    "Chi phí phải trả": "cost",
    "Quỹ khen thưởng, phúc lợi": "capital",
    "Đánh giá TSCĐVH theo giá trị hợp lý": "none",
    "Cổ phiếu quỹ": "treasury",
    "Cổ phiếu Quỹ": "treasury",
    "Tài sản cố định hữu hình": "asset",
    "Chênh lệch tỷ giá hối đoái": "exchange",
    "Đầu tư vào công ty liên kết, liên doanh ": "invest",
    "Đầu tư tài chính ngắn hạn": "invest_st",
    "Tài sản tài chính dài hạn": "total_assets",
    "Nguyên giá TSCĐ vô hình": "cogs",
    "Phải thu về cho vay ngắn hạn": "receivable",
    "Vốn của tổ chức tín dụng": "capital",
    "Góp vốn, đầu tư dài hạn": "equity",
    "Vay tài sản tài chính ngắn hạn": "debt",
    "Chi phí xây dựng cơ bản dở dang ": "cost",
    "Phải trả về xây dựng cơ bản": "payable",
    "Các khoản tương đương tiền": "cash",
    "Vay và nợ thuê tài sàn tài chính dài hạn": "debt_lt",
    "Doanh thu chưa thực hiện ": "unearned_revenue",
    "TỔNG CỘNG TÀI SẢN": "total_assets",
    "Vay ngắn hạn": "debt_st",
    "Nhận ký quỹ, ký cược dài hạn": "none",
    "Các công cụ tài chính phái sinh và các khoản nợ tài chính khác": "debt",
    "Chi phí sản xuất, kinh doanh dở dang ": "cost",
    "Thuế thu nhập hoãn lại phải trả": "tax",
    "Dự phòng toán học (trước 2014)": "expense",
    "Tài sản tài chính ngắn hạn": "asset",
    "Quỹ dự phòng tài chính": "capital",
    "Quỹ của tổ chức tín dụng": "capital",
    "Đầu tư vào công ty con ": "invest",
    "Dự phòng giảm giá chứng khoán đầu tư": "expense",
    "Tài sản ngắn hạn khác ": "assets",
    "Các khoản phải thu (từ 2016)": "receivable",
    "Tổng các khoản phải thu": "total_receivable",
    "Xây dựng cơ bản dở dang (trước 2015) ": "none",
    "Khấu hao lũy kế tài sản thuê tài chính": "depre_amort",
    "Nguyên giá tài sản thuê tài chính": "none",
    "Dự phòng giảm giá chứng khoán kinh doanh": "expense", #dự phòng-chi phí: expense
    "Tài sản cố định vô hình": "asset",
    "Phải thu về XDCB": "receivable",
    "Lãi chưa phân phối": "profit",
    "Quỹ khen thưởng , phúc lợi (trước 2010)": "capital",
    "Tài sản cố định": "asset",
    "Thuế VAT được khấu trừ": "tax",
    "Chênh lệch đánh giá lại tài sản": "diff_asset",
    "Trái phiếu chuyển đổi ngắn hạn": "none",
    "Phải trả hoạt động giao dịch chứng khoán": "payable",
    "Tài sản tái bảo hiểm ": "asset",
    "Chênh lệch tỷ giá": "exchange",
    "Quỹ dự trữ bắt buộc ": "none",
    "Thuế GTGT được khấu trừ": "none",
    "Dự phòng bồi thường nhượng tái bảo hiểm ": "expense",
    "Khấu hao lũy kế tài sản đầu tư": "depre_amort",
    "Giao dịch mua bán lại trái phiếu Chính phủ": "none",
    "Vốn khác": "equity",
    "Nguyên giá tài sản đầu tư": "cogs",
    "Ký quỹ bảo hiểm ": "none",
    "Phải thu về hợp đồng Bảo hiểm ": "receivable",
    "Các công cụ tài chính phái sinh và các tài sản tài chính khác": "asset",
    "Cổ phiếu ưu đãi ": "stock",
    "Tiền gửi tại Ngân hàng nhà nước Việt Nam": "cash",
    "Phát hành giấy tờ có giá": "none",
    "  Cho vay khách hàng": "none",
    "Lợi ích cổ đông thiểu số  ": "none",
    "Quyền chọn chuyển đổi trái phiếu": "none",
    "Phải trả khác": "payable",
    "Quỹ khen thưởng phúc lợi ": "capital",
    "Quỹ bảo vệ nhà đầu tư": "capital",
    "Trả trước người bán dài hạn ": "asset_lt",
    "TỔNG TÀI SẢN": "total_asset",
    "Dự phòng giảm giá đầu tư dài hạn": "expense",
    "Dự phòng giảm giá tài sản tài chính dài hạn": "expense",
    "GTCL tài sản cố định vô hình": "none",
    "Khấu hao lũy kế TSCĐ vô hình": "depre_amort",
    "Phải tả nội bộ dài hạn ": "payable",
    "Chênh lệch đánh giá lại tài sản ": "diff_asset",
    "Quỹ hỗ trợ sắp xếp doanh nghiệp ": "none",
    "Trả trước cho người bán": "none",
    "Thiết bị, vật tư, phụ tùng thay thế dài hạn": "none",
    "Phải thu các dịch vụ CTCK cung cấp ": "receivable",
    "Phải trả về lỗi giao dịch các tài sản tài chính": "payable",
    "Tạm ứng ": "none",
    "Thuế thu nhập hoãn lại phải thu": "receivable",
    "Dự phòng giảm giá HTK": "expense",
    "Khấu hao lũy kế bất động sản đầu tư": "depre_amort",
    "GTCL tài sản thuê tài chính": "none",
    "Cầm cố, thế chấp, ký quỹ và ký cược ngắn hạn": "none",
    "Dự phòng suy giảm giá trị TSNH khác": "expense",
    "Nguyên giá bất động sản đầu tư": "none",
    "Vốn kinh doanh ở các đơn vị trực thuộc": "none",
    "Vốn tài trợ, uỷ thác đầu tư của Chính phủ và các tổ chức tín dụng khác": "none",
    "Dự phòng bồi thường (trước 2014)": "expense",
    "Vốn góp": "equity",
    "Lợi nhuận đã thực hiện ": "none",
    "Thuế và các khoản phải trả Nhà nước": "tax",
    "NỢ PHẢI TRẢ": "debt",
    "Thặng dư vốn cổ phần ": "surplus",
    "Đầu tư ngắn hạn": "invest_st",
    "Hàng tồn kho": "inventory",
    "Quỹ phát triển khoa học công nghệ": "none",
    "Hàng tồn kho, ròng": "inventory",
    "TÀI SẢN NGẮN HẠN": "asset",
    "Giao dịch mua bán lại trái phiếu chính phủ": "none",
    "Thuế và các khoản phải thu của nhà nước": "receivable",
    "Phải thu dài hạn": "receivable_lt",
    "Các khoản đầu tư nắm giữ đến ngày đáo hạn (HTM)": "none",
    "Đầu tư nắm giữ đến ngày đáo hạn": "invest",
    "Các khoản trích nộp phúc lợi nhân viên": "cost",
    "Các tài sản dài hạn khác": "asset_lt",
    "Phải thu khách hàng dài hạn": "receivable_lt",
    "Các khoản phải thu": "receivable",
    "Lợi thế thương mại ": "profit",
    "Nguyên giá TSCĐ hữu hình": "cogs",
    "Phải trả khác cho người bán": "payable",
    "Phải thu thuế khác": "receivable",
    "Đầu tư vào công ty liên doanh": "invest",
    "Dự phòng toán học": "expense",
    "Investment properties": "invest",
    "Lợi nhuận chưa phân phối": "profit",
    "Other assets": "asset",
    "Phải thu nội bộ": "receivable",
    "TÀI SẢN DÀI HẠN": "total_asset_lt",
    "Bất động sản đầu tư": "invest",
    "Đánh giá TSCĐTTC theo giá trị hợp lý": "none",
    "Cho vay khách hàng": "asset",
    "Trái phiếu phát hành dài hạn": "bond",
    "Vốn đầu tư XDCB": "capital",
    "Phải thu về hoạt động giao dịch chứng khoán": "receivable",
    "Các khoản phải trả về thuế": "tax",
    "Vay dài hạn": "debt",
    "Tiền gửi của khách hàng": "cash",
    "Hàng tồn kho ": "inventory",
    "Dự phòng rủi ro cho vay khách hàng": "expense",
    "Vốn và các quỹ": "capital",
    "Quỹ bình ổn giá": "capital",
    "Đầu tư vào công ty con": "invest",
    "Tiền  ": "cash",
    "Phải thu nội bộ dài hạn": "receivable",
    "Chêch lệch tỷ giá": "exchange",
    "Lợi nhuận sau thuế chưa phân phối": "profit",
    "Vốn Ngân sách nhà nước và quỹ khác": "equity",
    "NỢ PHẢI TRẢ VÀ VỐN CHỦ SỞ HỮU": "equity_lib",
    "Doanh thu chưa thực hiện": "unearned_revenue",
    "Các khoản cho vay": "asset",
    "Nguồn kinh phí đã hình thành TSCĐ": "equity",
    "Tiền chi nộp quỹ hỗ trợ thanh toán ": "cost",
    "Phải trả về hợp đồng bảo hiểm ": "payable",
    "Khấu hao lũy kế TSCĐ hữu hình": "depre_amort",
    "Chi phí trả trước dài hạn": "cost",
    "Vay và nợ thuê tài chính ngắn hạn": "debt",
    "Người mua trả tiền trước ngắn hạn": "debt",
    "Tài sản dài hạn khác": "asset_lt",
    "Quỹ khen thưởng phúc lợi": "capital",
    "Lợi ích của cổ đông thiểu số": "profit",
    "Phải trả nhà cung cấp dài hạn": "payable",
    "Vay tài sản tài chính dài hạn": "debt",
    "Doanh thu hoa hồng chưa được hưởng": "sales",
    "Chi phí sản xuất, kinh doanh dở dang dài hạn": "cost",
    "Dự phòng trợ cấp mất việc làm ": "expense",
    "Phải thu về lỗi giao dịch CK": "receivable",
    "Các khoản phải thu ": "receivable",
    "Trả trước người bán dài hạn": "asset_st",
    "Vốn ngân sách nhà nước  ": "equity",
    "TÀI SẢN DÀI HẠN ": "total_asset_lt",
    "Phải trả nội bộ về vốn kinh doanh": "payable",
    "Vật tư văn phòng, công cụ, dụng cụ": "asset",
    "Đánh giá TSCĐHH theo giá trị hợp lý": "none",
    "Doanh thu chưa thực hiện ngắn hạn": "unearned_revenue",
    "Tiền gửi và vay các Tổ chức tín dụng khác": "debt",
    "Thặng dư vốn cổ phần": "surplus",
    "Phải thu của khách hàng": "receivable",
    "Tiền mặt, vàng bạc, đá quý": "asset",
    "Đầu tư vào công ty liên kết ": "invest",
    "Phải trả người lao động": "payable",
    "Xây dựng cơ bản dở dang   ": "none",
    "Vay quỹ hỗ trợ thanh toán": "debt",
    "Cổ phiếu ưu đãi": "stock",
    "Trả trước ngắn hạn": "asset",
    "Giá trị thuần đầu tư ngắn hạn": "none",
    "Cổ phiếu phổ thông": "stock",
    "Vốn ngân sách nhà nước": "equity",
    "Dự phòng chia lãi": "expense",
    "Các tài sản tài chính ghi nhận thông qua lãi/lỗ (FVTPL)": "none",
    "Phải trả dài hạn khác": "payable",
    "Nhận ký quỹ, ký cược ngắn hạn": "none",
    "Tiền gửi tại các TCTD khác và cho vay các TCTD khác": "debt",
    "Lợi ích cổ đông thiểu số": "dividends",
    "Phải trả thương mại": "payable",
    "Phải trả nội bộ dài hạn": "payable",
    "Quỹ dự phòng tài chính ": "expense",
    "Doanh thu chưa thực hiên": "unearned_revenue",
    "Dự phòng trợ cấp thôi việc": "expense",
    "Các khoản nợ chính phủ và NHNN Việt Nam": "debt",
    "Dự phòng phí nhượng tái bảo hiểm ": "expense",
    "Người mua trả tiền trước": "none",
    "Quỹ khác": "capital",
    "Thuế VAT phải thu": "tax",
    "Tiền và tương đương tiền ": "cash",
    "Giao dịch mua bán lại trái phiếu ": "none",
    "Đầu tư dài hạn": "invest_lt",
    "Phải thu khách hàng ": "receivable",
    "Trái phiếu chuyển đổi": "stock",
    "Tài sản lưu động khác": "asset",
    "Dự phòng các khoản công nợ dài hạn": "expense",
    "Tài sản ngắn hạn khác": "asset_st",

# Cashflow
    "Phải thu hoạt động BH gốc": "none",
    "(+) Tăng, (-) giảm phải trả khác": "payable",
    "Lãi/lỗ từ hoạt động đầu tư": "glce",
    "Phải trả hoạt động nhượng tái BH": "payable",
    "Tiền chi nộp thuế thu nhập doanh nghiệp": "none",
    "Lỗ suy giảm giá trị các khoản đầu tư nắm giữ đến ngày đáo hạn": "none",
    "(+) Tăng, (-) giảm thuế TNDN CTCK đã nộp ": "none",
    "(-) Tăng, (+) giảm các khoản phải thu khác": "none",
    "Lãi về ghi nhận chêch lệch đánh giá theo giá trị hợp lý tài sản tài chính sẵn sàng để bán AFS khi phân loại lại": "none",
    "Tiền chi trả nợ gốc vay": "none",
    "Lãi đánh giá giá trị các công nợ tài chính thông qua kết quả kinh doanh": "none",
    "(+) Tăng, (-) giảm phải trả người lao động": "payable",
    "Tiền và tương đương tiền cuối kỳ": "cash",
    "Lưu chuyển thuần từ hoạt động kinh doanh chứng khoán": "cashflow",
    "Cổ tức, lợi nhuận đã trả cho chủ sở hữu": "profit",
    "Tiền chi từ thanh lý, nhượng bán TSCĐ": "cost",
    "Tiền thu hồi đầu tư góp vốn vào đơn vị khác": "cost",
    "(Tăng)/Giảm các khoản tiền gửi và cho vay các tổ chức tín dụng khác": "cashflow",
    "Lưu chuyển tiền thuần từ hoạt động tài chính": "cashflow",
    "Tiền thu từ phát hành cổ phiếu và vốn góp": "cash",
    "Tăng/giảm vay tài sản tài chính": "debt",
    "nan": "none",
    "Phân bổ lợi thế thương mại": "profit",
    "Lưu chuyển từ hoạt động đầu tư": "cashflow",
    "Hoàn nhập suy giảm giá trị của các tài sản tài chính sẵn sàng để bán": "none",
    "Tiền và các khoảng tương đương tiền cuối kỳ": "cash",
    "Lãi, lỗ hoạt động đầu tư": "profit",
    "Tăng/(Giảm) tiền gửi của khách hàng": "cashflow",
    "Phải trả hoạt động BH gốc": "payable",
    "Lỗ đánh giá giá trị các công cụ tài chính phái sinh": "none",
    "(+) Tăng, (-) giảm phải trả Tổ chức phát hành chứng khoán": "payable",
    "(+) Tăng, (-) giảm phải trả về lỗi giao dịch các tài sản tài chính": "payable",
    "Tăng/(Giảm) khác về công nợ hoạt động": "cashflow",
    "Tiền lãi vay đã trả": "i-payable",
    "(-) Tăng, (+) giảm chi phí phải trả (không bao gồm chi phí lãi vay)": "payable",
    "Tăng/(Giảm) lãi, phí phải trả": "payable",
    "Suy giảm giá trị của các tài sản tài chính sẵn sàng để bán ": "none",
    "Lãi/lỗ chêch lệch tỷ giá hối đoái": "glce",
    "Tiền thu khác từ hoạt động kinh doanh": "cash",
    "Tăng/giảm các khoản cho vay ": "cashflow",
    "Lãi, lỗ chêch lệch tỷ giá hối đoái chưa thực hiện": "cashflow",
    "Tiền chi mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác": "cash",
    "Tiền và tương đương tiền đầu kỳ": "cash",
    "Tăng/(Giảm) các khoản nợ chính phủ và NHNN": "cashflow",
    "Lưu chuyển tiền thuần trong kỳ": "cashflow",
    "(Tăng)/Giảm khác về tài sản hoạt động": "cashflow",
    "Tiền thu từ việc bán các khoản đầu tư vào các doanh nghiệp khác": "cash",
    "Đầu tư vào các doanh nghiệp khác": "invest",
    "Tăng/giảm các khoản phải trả (không kể lãi vay phải trả, thuế thu nhập phải nộp)": "payable",
    "Cổ tức và tiền lãi nhận được": "stock",
    "Tiền vay Quỹ Hỗ Trợ thanh toán ": "debt",
    "Giảm các doanh thu phi tiền tệ": "none",
    "Thu lãi và cổ tức ": "profit",
    "Tiền chi thanh toán giấy tờ có giá dài hạn đủ điều kiện tính vào vốn tự có và các khoản vốn vay dài hạn khác": "debt",
    "Tiền gửi tại NHNN": "cáh",
    "Phải trả hoạt động khác": "payable",
    "Tăng/(Giảm) các khoản tiền gửi và vay các TCTD khác": "cashflow",
    "Thuế thu nhập doanh nghiệp đã trả": "tax",
    "Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác": "none",
    "Các khoản tương đương tiền": "cash",
    "Thu nhập lãi và các khoản tương đương": "income",
    "Lãi/lỗ trước những thay đổi vốn lưu động": "glce",
    "Khấu hao TSCĐ": "depre_amort",
    "Chi phí lãi và các khoản tương đương": "cost",
    "Phải trả CBCNV": "payable",
    "Thuế thu nhập doanh nghiệp đã nộp": "none",
    "Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác": "none",
    "Tăng/giảm chứng khoán kinh doanh": "none",
    "Lỗ đánh giá giá trị các công nợ tài chính ghi nhận thông qua KQKD": "lost",
    "Tăng/giảm tài sản tài chính ghi nhận thông qua lãi lỗ": "cashflow",
    "Tăng các chi phí tiền tệ": "cost",
    "Cổ tức đã trả": "stock",
    "(Tăng)/Giảm các công cụ tài chính phái sinh và các tài sản tài chính khác": "cashflow",
    "Hoàn nhập chi phí dự phòng": "cost",
    "(+) Tăng, (-) giảm phải trả cho người bán": "payable",
    "Thu nhập khác": "income",
    "Tiền thu được do bán cổ phiếu quỹ": "cash",
    "Lưu chuyển tiền thuần từ hoạt động đầu tư": "cashflow",
    "Lãi đánh giá giá trị tài sản tài chính ghi nhận thông qua lãi/lỗ FVTPL": "profit",
    "Tiền thu hồi đầu tư vào đơn vị khác": "cash",
    "Khấu hao tài sản cố định": "depre_amort",
    "Lãi từ thanh lý các khoản cho vay và phải thu": "i-receivable",
    "Các khoản dự phòng": "expense",
    "Tăng/(Giảm) các công cụ tài chính phái sinh và các khoản nợ tài chính khác": "none",
    "Tiền thu được từ thanh lý tài sản cố định": "profit",
    "(-) Tăng, (+) giảm các khoản phải thu về lỗi giao dịch các TSTC": "cashflow",
    "Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác": "none",
    "(-) Tăng, (+) giảm các khoản phải thu các dịch vụ CTCK cung cấp ": "cashflow",
    "Tăng/giảm các khoản đầu tư giữ đến ngày đáo hạn": "cashflow",
    "Tiền thu từ phát hành giấy tờ có giá dài hạn đủ điều kiện tính vào vốn tự có và các khoản vốn vay dài hạn khác": "cash",
    "Thanh toán cho nhân viên và nhà cung cấp": "cost",
    "Tăng/giảm hàng tồn kho": "inventory",
    "Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu": "none",
    "(Tăng)/giảm các khoản về kinh doanh chứng khoán": "cashflow",
    "(Tăng)/Giảm lãi, phí phải thu": "cashflow",
    "Dự thu tiền lãi": "none",
    "Tiền chi ra mua cổ phiếu quỹ": "none",
    "Lãi đánh giá giá trị các công cụ tài chính phái sinh cho mục đích phòng ngừa": "none",
    "Lưu chuyển tiền từ hoạt động tài chính": "none",
    "Tiền mua tài sản cố định và các tài sản dài hạn khác": "none",
    "Lợi nhuận trước thuế": "ebt",
    "Tăng/giảm các khoản phải thu": "none",
    "Chi từ các quỹ của TCTD": "none",
    "Chi phí lãi vay": "cost",
    "Thay đổi tài sản và nợ phải trả hoạt động": "debt",
    "Phải trả hoạt động nhận tái BH": "payable",
    "Tăng/giảm vay và nợ thuê tài sản tài chính": "debt",
    "Tăng/giảm các tài sản khác": "cashflow",
    "Lỗ đánh giá giá trị các tài sản tài chính ghi nhận thông qua lãi/lỗ FVTPL": "lost",
    "Lỗ từ thanh lý các khoản đầu tư vào công ty con và công ty liên doanh, liên kết": "lost",
    "Suy giảm giá trị của các tài sản cố định, BĐSĐT": "none",
    "Lãi từ thanh lý các khoản đầu tư vào công ty con và công ty liên doanh, liên kết": "none",
    "Lỗ suy giảm giá trị các khoản cho vay": "none",
    "Phải thu/trả đơn vị nội bộ": "receivable",
    "Thu nhập từ hoạt động kinh doanh chứng khoán": "income",
    "Lưu chuyển thuần từ hoạt động tài chính": "cashflow",
    "Các khoản điều chỉnh khác": "none",
    "Tiền vay ngắn hạn, dài hạn nhận được": "cash_debt",
    "Tiền thu các khoản nợ đã được xử lý, xóa, bù đắp bằng nguồn rủi ro": "none",
    "Lỗ đánh giá giá các công cụ tài chính phát sinh cho mục đích phòng ngừa rủi ro": "none",
    "Tiền vay khác": "cash_debt",
    "Phải thu hoạt động nhượng tái BH": "receivable",
    "Lưu chuyển tiền thuần từ hoạt động kinh doanh": "cashflow",
    "Tăng/(Giảm) vốn tài trợ, uỷ thác đầu tư của chính phủ và các TCTD khác": "none",
    "Chi phí phải trả, chi phí trả trước": "payable_cost",
    "Lưu chuyển tiền thuần từ các hoạt động sản xuất kinh doanh": "none",
    "Mua sắm Bất động sản đầu tư": "",
    "Tăng/(Giảm) nguồn dự phòng để bù đắp tổn thất các khoản": "none",
    "(+) Tăng, (-) giảm thuế và các khoản phải nộp Nhà nước": "none",
    "Tiền chi trả gốc nợ vay khác": "cost",
    'Chêch lệch đánh giá lại tài sản ': "none",
    "Thu nhập từ hoạt động dịch vụ nhận được": "income",
    "Lỗ về ghi nhận chêch lệch đánh giá theo giá trị hợp lý tài sản tài chính sẵn sàng để bán AFS khi phân loại lại": "none",
    "(-) Tăng, (+) giảm phải thu và dự thu cổ tức, tiền lãi các tài sản tài chính": "receivable",
    "Ảnh hưởng của chênh lệch tỷ giá": "exchange",
    "(-) Tăng, (+) giảm phải thu bán các tài sản tài chính ghi nhận thông qua lãi/lỗ FVTPL": "receivable",
    "Tiền mặt, tiền gửi ngân hàng đầu kỳ": "none",
    "Tiền chi đầu tư góp vốn vào đơn vị khác": "none",
    "Lỗ khác": "lost",
    "Lưu chuyển tiền thuần từ hoạt động kinh doanh trước thuế thu nhập DN": "cashflow",
    "Tăng/giảm Trái phiếu chuyển đổi - Cấu phần nợ": "cashflow",
    "Tiền chi trả vốn góp cho các chủ sở hữu, mua lại cổ phiếu của doanh nghiệp đã phát hành": "none",
    "Cổ tức, lợi nhuận đã trả cho chủ sở hữ": "profit",
    "Tăng/giảm vay Quỹ hỗ trợ Thanh toán": "debt",
    "Lãi từ thanh lý tài sản cố định, BĐSĐT": "profit",
    "Tiền thu từ bán, thanh lý bất động sản đầu tư": "revenue",
    "(Tăng)/Giảm các khoản cho vay khách hàng": "none",
    "Thu được từ nợ khó đòi": "revenue",
    "Lợi nhuận từ hoạt động kinh doanh trước thay đổi vốn lưu động": "profit",
    "Tiền vay ngắn hạn, dài hạn được nhận": "cash_debt",
    "Lãi từ thanh lý các tài sản tài chính sẵn sàng để bán khi phân loại lại": "profit",
    "Tăng/giảm tài sản tài chính sẵn sàng để bán AFS": "none",
    "Chi phí dự phòng suy giảm giá trị các khoản đầu tư tài chính dài hạn": "cost",
    "Tiền chi trả nợ thuê tài chính": "cost",
    "(+) Tăng, (-) giảm các khoản trích nộp phúc lợi nhân viên": "none",
    "Tiền và các khoản tương đương tiền đầu kỳ": "cash",
    "Phải thu hoạt động khác": "receivable",
    "Tiền chi trả gốc vay Quỹ Hỗ Trợ thanh toán": "cost",
    "Tiền chi ra do bán, thanh lý bất động sản đầu tư": "cost",
    "Tăng/(Giảm) phát hành giấy tờ có giá": "none",
    "Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ": "none",
    "Tiền thu phát hành cổ phiếu, nhận vốn góp của chủ sở hữu": "none",
    "Điều chỉnh cho các khoản": "none",
    "Tiền chi khác từ hoạt động kinh doanh": "none",
    "Tiền chi cho vay, mua các công cụ nợ của đơn vị khác": "cost",
    "Lỗ từ thanh lý TSCĐ": "lost",
    "Lỗ từ thanh lý các tài sản tài chính sẵn sàng để bán": "lost",
    "Phải thu hoạt động nhận tái BH": "receivable",
    "Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia": "profit",
    "Tăng/giảm chi phí trả trước": "cost",
    "Tăng/giảm các khoản phải thu bán các tài sản tài chính": "receivable",
    "Tiền chi khác cho hoạt động kinh doanh": "cost",
    "Lãi khác": "profit",
    "Tăng/giảm Trái phiếu phát hành": "cashflow",
    "Ảnh hưởng của thay đổi tỷ giá hối đoán quy đổi ngoại tệ": "exchange",
    "Tiền chi trả nợ gốc vay tài sản tài chính": "cost",    
}
